---
# tasks file for ansible-role-vagrant

- name: Include OS specific variables.
  ansible.builtin.include_vars: "{{ ansible_system }}.yml"

- name: Install Vagrant
  ansible.builtin.include_tasks: "setup-{{ ansible_system }}.yml"

- name: Install Vagrant plugins
  ansible.builtin.include_tasks: "vagrant-plugins.yml"
  when: vagrant_plugins | length > 0
