---
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: linux
    image: ${namespace:-diodonfrost}/${image:-ansible-ubuntu:22.04}
    command: ${command:-"sleep 999"}
    privileged: true
    pre_build_image: yes
provisioner:
  name: ansible
verifier:
  name: ansible
