---
- name: Verify
  hosts: all
  tasks:
    - name: Linux | Get vagrant version used in Molecule
      ansible.builtin.set_fact:
        molecule_vagrant_version: "{{ lookup('env', 'vagrant_version') | default('latest', true) }}"

    - name: Linux | Vagrant should be functionnal
      ansible.builtin.command: vagrant --version
      register: vagrant_result

    - name: Linux | Verify vagrant is functionnal
      ansible.builtin.assert:
        that:
          - vagrant_result.rc == 0
        success_msg: "All tests passed"

    - name: Linux | Verify the vagrant version installed
      ansible.builtin.assert:
        that:
          - molecule_vagrant_version in vagrant_result.stdout
        success_msg: "All tests passed"
      when: molecule_vagrant_version != "latest"
